<?php

return [
    [
        'id' => 'test_1',
        'language' => 'English',
        'skill' => 'Reading Accuracy',
        'title' => 'Test 1: Correct Reading',
        'difficulty' => 'Beginner',
        'instruction' => 'Read the passage exactly as written.',
        'display_text' => 'The little boy went to school early in the morning. He carried his books and greeted his teacher with a smile.',
        'gemini_context' => "You are evaluating a student's English reading accuracy.\n\nThe expected passage is:\n\"The little boy went to school early in the morning. He carried his books and greeted his teacher with a smile.\"\n\nListen carefully to the attached audio.\n\nYour tasks:\n1. Transcribe exactly what the student says.\n2. Compare the spoken words against the expected passage.\n3. Identify correctly spoken words.\n4. Identify skipped words.\n5. Identify substituted or incorrect words.\n6. Identify added words.\n7. Identify repeated words.\n8. Calculate an estimated word accuracy percentage.\n9. Explain every detected mistake.\n10. Identify uncertain portions instead of guessing.\n\nImportant rules:\n- Do not automatically correct the student's speech.\n- Do not assume the student read the expected text correctly.\n- Do not penalize valid accent differences.\n- Do not invent mistakes.\n- Base your evaluation on the actual audio.\n\nReturn a clear table of detected errors and a final summary.",
    ],
    [
        'id' => 'test_2',
        'language' => 'English',
        'skill' => 'Reading Accuracy',
        'title' => 'Test 2: Reading with Mistakes',
        'difficulty' => 'Intermediate',
        'instruction' => "Display the original passage as the expected text, but instruct me to deliberately:\n- Skip \"early\"\n- Say \"bag\" instead of \"books\"\n- Repeat \"teacher\" twice",
        'display_text' => 'The little boy went to school early in the morning. He carried his books and greeted his teacher with a smile.',
        'gemini_context' => "You are evaluating a student's English reading accuracy.\n\nThe expected passage is:\n\"The little boy went to school early in the morning. He carried his books and greeted his teacher with a smile.\"\n\nListen carefully to the attached audio.\n\nYour tasks:\n1. Transcribe exactly what the student says.\n2. Compare the spoken words against the expected passage.\n3. Identify correctly spoken words.\n4. Identify skipped words.\n5. Identify substituted or incorrect words.\n6. Identify added words.\n7. Identify repeated words.\n8. Calculate an estimated word accuracy percentage.\n9. Explain every detected mistake.\n10. Identify uncertain portions instead of guessing.\n\nImportant rules:\n- Do not automatically correct the student's speech.\n- Do not assume the student read the expected text correctly.\n- Do not penalize valid accent differences.\n- Do not invent mistakes.\n- Base your evaluation on the actual audio.\n\nReturn a clear table of detected errors and a final summary.",
    ],
    [
        'id' => 'test_3',
        'language' => 'English',
        'skill' => 'Reading Accuracy',
        'title' => 'Test 3: Incomplete Reading',
        'difficulty' => 'Beginner',
        'instruction' => 'Read only the first sentence and stop.',
        'display_text' => 'The little boy went to school early in the morning. He carried his books and greeted his teacher with a smile.',
        'gemini_context' => "You are evaluating a student's English reading accuracy.\n\nThe expected passage is:\n\"The little boy went to school early in the morning. He carried his books and greeted his teacher with a smile.\"\n\nListen carefully to the attached audio.\n\nYour tasks:\n1. Transcribe exactly what the student says.\n2. Compare the spoken words against the expected passage.\n3. Identify correctly spoken words.\n4. Identify skipped words.\n5. Identify substituted or incorrect words.\n6. Identify added words.\n7. Identify repeated words.\n8. Calculate an estimated word accuracy percentage.\n9. Explain every detected mistake.\n10. Identify uncertain portions instead of guessing.\n\nImportant rules:\n- Do not automatically correct the student's speech.\n- Do not assume the student read the expected text correctly.\n- Do not penalize valid accent differences.\n- Do not invent mistakes.\n- Base your evaluation on the actual audio.\n\nReturn a clear table of detected errors and a final summary.",
    ],
    [
        'id' => 'test_4',
        'language' => 'English',
        'skill' => 'Pronunciation',
        'title' => 'Test 4: Individual Words',
        'difficulty' => 'Beginner',
        'instruction' => 'Pronounce each word clearly, with a short pause between words.',
        'display_text' => "Three\nThink\nSchool\nVegetable\nMathematics\nComfortable",
        'gemini_context' => "Evaluate the pronunciation of each expected English word in the attached audio.\n\nExpected words: Three, Think, School, Vegetable, Mathematics, Comfortable.\n\nFor every word:\n- Identify whether it was spoken.\n- Evaluate its pronunciation.\n- Identify specific audible sound errors.\n- Distinguish accent variations from genuine errors.\n- Do not assume accurate transcription proves correct pronunciation.\n- Report uncertainty when sound-level evaluation is unreliable.\n\nReturn a table with: Expected Word | Detected Word | Pronunciation Result | Error Explanation",
    ],
    [
        'id' => 'test_5',
        'language' => 'English',
        'skill' => 'Pronunciation',
        'title' => 'Test 5: Similar Sounds',
        'difficulty' => 'Intermediate',
        'instruction' => 'Read each pair in the displayed order.',
        'display_text' => "Think / Sink\nThree / Tree\nShip / Sheep\nFan / Van",
        'gemini_context' => "Evaluate the pronunciation of each expected English word in the attached audio.\n\nExpected word pairs: Think / Sink, Three / Tree, Ship / Sheep, Fan / Van.\n\nFor every word:\n- Identify whether it was spoken.\n- Evaluate its pronunciation.\n- Identify specific audible sound errors.\n- Distinguish accent variations from genuine errors.\n- Do not assume accurate transcription proves correct pronunciation.\n- Report uncertainty when sound-level evaluation is unreliable.\n\nReturn a table with: Expected Word | Detected Word | Pronunciation Result | Error Explanation. Assess whether the spoken sounds are distinguishable, without relying only on transcription.",
    ],
    [
        'id' => 'test_6',
        'language' => 'English',
        'skill' => 'Reading Fluency',
        'title' => 'Test 6: Fluency',
        'difficulty' => 'Intermediate',
        'instruction' => 'Read naturally.',
        'display_text' => "Every morning, Sara wakes up early and prepares for school. She enjoys reading books and learning new things. Sometimes she finds difficult words, but she tries again until she understands them.",
        'gemini_context' => "Evaluate the student's reading fluency using the attached audio.\n\nExpected passage:\n\"Every morning, Sara wakes up early and prepares for school. She enjoys reading books and learning new things. Sometimes she finds difficult words, but she tries again until she understands them.\"\n\nAssess:\n- Reading continuity\n- Pauses\n- Hesitations\n- Repetitions\n- Reading pace\n- Expression\n\nExplain each observation using evidence from the recording.\n\nDo not confuse slow reading with incorrect reading.",
    ],
    [
        'id' => 'test_7',
        'language' => 'English',
        'skill' => 'Speaking',
        'title' => 'Test 7: Picture-Free Speaking',
        'difficulty' => 'Advanced',
        'instruction' => 'Speak for approximately 30–60 seconds.',
        'display_text' => "Tell me about your school and what you enjoy doing there.",
        'gemini_context' => "Evaluate the student's speaking skills using the attached audio.\n\nQuestion: \"Tell me about your school and what you enjoy doing there.\"\n\nEvaluate:\n- Relevance\n- Grammar\n- Vocabulary\n- Sentence formation\n- Clarity\n- Fluency\n\nReturn criterion-wise observations and scores where justified.",
    ],
    [
        'id' => 'test_8',
        'language' => 'Hindi',
        'skill' => 'Reading Accuracy',
        'title' => 'Test 8: Hindi Reading',
        'difficulty' => 'Beginner',
        'instruction' => 'Read the passage aloud.',
        'display_text' => "राम सुबह जल्दी उठता है। वह रोज़ स्कूल जाता है और मन लगाकर पढ़ाई करता है।",
        'gemini_context' => "Evaluate the student's Hindi reading accuracy.\n\nExpected passage: \"राम सुबह जल्दी उठता है। वह रोज़ स्कूल जाता है और मन लगाकर पढ़ाई करता है।\"\n\nTranscribe the actual spoken content in Devanagari.\n\nCompare it with the expected passage.\n\nIdentify:\n- Correct words\n- Skipped words\n- Incorrect words\n- Added words\n- Repeated words\n\nExplain detected mistakes in English.\n\nDo not silently correct the student's speech.",
    ],
    [
        'id' => 'test_9',
        'language' => 'Urdu',
        'skill' => 'Reading Accuracy',
        'title' => 'Test 9: Urdu Reading',
        'difficulty' => 'Beginner',
        'instruction' => 'Read the passage aloud.',
        'display_text' => "علی صبح جلدی اٹھتا ہے۔ وہ روز اسکول جاتا ہے اور دل لگا کر پڑھتا ہے۔",
        'gemini_context' => "Evaluate the student's Urdu reading accuracy.\n\nExpected passage: \"علی صبح جلدی اٹھتا ہے۔ وہ روز اسکول جاتا ہے اور دل لگا کر پڑھتا ہے۔\"\n\nTranscribe the actual spoken content in Urdu script.\n\nCompare it with the expected passage.\n\nIdentify:\n- Correct words\n- Skipped words\n- Incorrect words\n- Added words\n- Repeated words\n\nExplain detected mistakes in English.\n\nDo not silently correct the student's speech.",
    ],
    [
        'id' => 'test_10',
        'language' => 'Arabic/Qaida',
        'skill' => 'Letter Recognition',
        'title' => 'Test 10: Arabic Letters',
        'difficulty' => 'Beginner',
        'instruction' => 'Read the displayed letters individually.',
        'display_text' => "ا ب ت ث ج ح خ",
        'gemini_context' => "Evaluate the student's Arabic Qaida Letter Recognition.\n\nLetters: ا ب ت ث ج ح خ\n\nListen to each spoken sound separately.\nCompare the spoken sound against the expected letter.\n\nGemini should assess each spoken letter separately. Do not assume the student pronounced the sounds correctly merely because the expected text is provided. Report uncertainty when the audio cannot reliably distinguish the sounds.",
    ],
    [
        'id' => 'test_11',
        'language' => 'Arabic/Qaida',
        'skill' => 'Harakat',
        'title' => 'Test 11: Harakat',
        'difficulty' => 'Beginner',
        'instruction' => 'Read each letter with its displayed Harakat.',
        'display_text' => "بَ بِ بُ\nتَ تِ تُ\nمَ مِ مُ",
        'gemini_context' => "Evaluate the student's Arabic Qaida Harakat reading.\n\nExpected sequence:\nبَ بِ بُ\nتَ تِ تُ\nمَ مِ مُ\n\nListen to each spoken sound separately.\nCompare the spoken sound against the expected letter and vowel combination.\n\nCheck:\n- Fatha\n- Kasra\n- Damma\n- Letter recognition\n- Vowel substitutions\n- Missing sounds\n- Repeated sounds\n\nProvide an individual result for each sound.\nDo not assume the student pronounced the sounds correctly merely because the expected text is provided.\nReport uncertainty when the audio cannot reliably distinguish the sounds.",
    ],
    [
        'id' => 'test_12',
        'language' => 'Arabic/Qaida',
        'skill' => 'Madd',
        'title' => 'Test 12: Madd',
        'difficulty' => 'Intermediate',
        'instruction' => 'Read each combination while observing the long vowel.',
        'display_text' => "بَا بِي بُو\nتَا تِي تُو",
        'gemini_context' => "Evaluate the student's Arabic Qaida Madd reading.\n\nExpected sequence:\nبَا بِي بُو\nتَا تِي تُو\n\nListen to each spoken sound separately.\nCompare the spoken sound against the expected combination.\n\nEvaluate whether long vowel sounds are produced correctly, reporting uncertainty when duration or articulation cannot be judged reliably.",
    ],
    [
        'id' => 'test_13',
        'language' => 'Arabic/Qaida',
        'skill' => 'Makhraj',
        'title' => 'Test 13: Makhraj Experiment',
        'difficulty' => 'Advanced',
        'instruction' => 'Pronounce each letter separately and clearly.',
        'display_text' => "ح ه\nع أ\nق ك\nص س\nط ت",
        'gemini_context' => "Evaluate the student's Arabic Qaida Makhraj.\n\nLetters:\nح ه\nع أ\nق ك\nص س\nط ت\n\nListen to each spoken sound separately.\nCompare the spoken sound against the expected letter.\n\nGemini should attempt to identify articulation differences.\n\nDo not treat successful letter transcription as proof of correct Makhraj. Mark this test as Experimental.",
    ]
];
